### PR TITLE
fix: Use `bitRate` multiplier instead of setting it to an absolute value

### LINKED ISSUE #2208: 🐛 `CameraDevice` contains formats that are not supported by `CamcorderProfile`
### What's happening?

When the video resolution is too high, recording does not work unless I use the H.265 codec.

Is it possible to know when to use the H.265 codec?

For example:
 - working with h264/h265: {"autoFocusSystem": "contrast-detection", "fieldOfView": 78.63484214515682, "maxExposure": 8, "maxFps": 30, "maxISO": 6400, "maxZoom": 10, "minExposure": -8, "minFps": 1, "minISO": 50, "photoHeight": 2736, "photoWidth": 3648, "pixelFormats": ["yuv", "native"], "supportsDepthCapture": true, "supportsPhotoHdr": false, "supportsVideoHdr": false, "videoHeight": 2056, "videoStabilizationModes": ["off", "standard", "cinematic-extended"], "videoWidth": 3648}
- not working with h264 (/ working with h265): {"autoFocusSystem": "contrast-detection", "fieldOfView": 78.63484214515682, "maxExposure": 8, "maxFps": 30, "maxISO": 6400, "maxZoom": 10, "minExposure": -8, "minFps": 1, "minISO": 50, "photoHeight": 2736, "photoWidth": 3648, "pixelFormats": ["yuv", "native"], "supportsDepthCapture": true, "supportsPhotoHdr": false, "supportsVideoHdr": false, "videoHeight": 2736, "videoStabilizationModes": ["off", "standard", "cinematic-extended"], "videoWidth": 3648}

### Reproduceable Code

```tsx
const devices = Camera.getAvailableCameraDevices();
const device = devices.find((d) => d.position === 'back');
if (!device) {
    return;
}
const format = getCameraFormat(device, [
    { videoResolution: 'max' },
]);

// ...

return (
    <View style={s.container}>
        <Camera
            ref={this.cameraRef}
            style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }}
            device={device}
            format={format}
            isActive={true}
            video={true}
            audio={true}
            resizeMode='contain'
        />
    </View>
);
```

### Relevant log output

```shell
{"cause": {"message": "prepare failed.", "stacktrace": "java.io.IOException: prepare failed.
	at android.media.MediaRecorder._prepare(Native Method)
	at android.media.MediaRecorder.prepare(MediaRecorder.java:1107)
	at com.mrousavy.camera.core.RecordingSession.start(RecordingSession.kt:91)
	at com.mrousavy.camera.core.CameraSession.startRecording(CameraSession.kt:546)
	at com.mrousavy.camera.CameraView_RecordVideoKt.startRecording(CameraView+RecordVideo.kt:56)
	at com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
"}, "code": "capture/unknown", "message": "An unknown error occurred while trying to start a video recording! prepare failed.", "userInfo": null}
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "limited",
  "maxZoom": 10,
  "minZoom": 1,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera",
    "ultra-wide-angle-camera",
    "telephoto-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": true,
  "name": "BACK (0)",
  "hasFlash": true,
  "hasTorch": true,
  "position": "back",
  "id": "0"
}
```

### Device

HUAWEI P30 (ELE-L29) with Android 10

### VisionCamera Version

3.6.10

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by mrousavy**
## What

Uses a bit-rate multiplier instead of trying to calculate bit-rate. This is much more reliable as the single source of truth comes from the hardware encoder.

The following values give the following bitrates on my iPhone 8:

```
undefined: 23328000
'low':     18662400
'normal':  23328000
'high':    27993600
12.345678: 12345678
50:        50000000
```

Also, this fixes the bit-rate settings for Android by actually using recommended values instead of just calculating it ourselves, which was often wrong.

## Related issues

* Fixes https://github.com/mrousavy/react-native-vision-camera/issues/2208

### CODE REVIEW

File: package/android/src/main/java/com/mrousavy/camera/types/RecordVideoOptions.kt [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+  init {
+    if (map.hasKey("fileType")) {
+      fileType = VideoFileType.fromUnionValue(map.getString("fileType"))
+    }
+    if (map.hasKey("flash")) {
+      flash = Flash.fromUnionValue(map.getString("flash"))
+    }
+    if (map.hasKey("videoCodec")) {
+      videoCodec = VideoCodec.fromUnionValue(map.getString("fileType"))
```
Comment (j-jonathan) [inline package/android/src/main/java/com/mrousavy/camera/types/RecordVideoOptions.kt:20]: Is it normal that you used 'map.getString("fileType")' instead of 'map.getString("videoCoded")'? (i'm just trying to understand the changes)

Comment (mrousavy) [reply package/android/src/main/java/com/mrousavy/camera/types/RecordVideoOptions.kt:20]: Whoops, that's a typo.
Nice spot mate, I'll fix it right away thanks!
