### PR TITLE
fix: Fix Recordings with `audio={false}` timeouting

### LINKED ISSUE #2218: 🐛 Disabled Audio has 5-10 seconds delay in finish video recording
### What's happening?

My Camera app has 2 options one to record video with audio and one to record without audio, I noticed when I finish recording when the audio is `false` `audio={false}` it has a `5 - 10` seconds delay in comparison with when the Audio is enabled `audio={true}` which it trigger `onRecordingFinished: async (video) => {}` immediately when finish recording

### Reproduceable Code

```tsx
`
 <ReanimatedCamera
            style={[{           
                height: height,
                width: "100%",
                zIndex: -2,
                borderRadius: 30,
                overflow: 'hidden'
            }]}
            ref={cameraRef}
            device={device}
            isActive={true}
            torch={flash}
            photo={true}
            zoom={Math.abs(cameraZoomValue * 1000)}
            video={true}
            audio={captureAudio}
            format={format}
            fps={30}  
            enableZoomGesture
            orientation="portrait"
        />
`
```

### Relevant log output

```shell
No logs
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "full",
  "isMultiCam": false,
  "minZoom": 1,
  "position": "back",
  "supportsRawCapture": false,
  "supportsFocus": true,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsLowLightBoost": false,
  "maxZoom": 123.75,
  "name": "Back Camera",
  "hasFlash": true,
}
```

### Device

iPhone 12

### VisionCamera Version

3.6.10

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by mrousavy**
## What

Fixes Recordings with `audio={false}` from timeouting by finishing the audio track immediately when it is not enabled.

## Related issues

- Fixes #2218

### CODE REVIEW

File: package/ios/Core/RecordingSession.swift [hunk 1]
```diff
@@ -152,6 +152,11 @@ class RecordingSession {
     assetWriter.startSession(atSourceTime: currentTime)
     startTimestamp = currentTime
     ReactLogger.log(level: .info, message: "Started RecordingSession at time: \(currentTime.seconds)")
+
+    if audioWriter == nil {
+      // Audio was enabled, mark the Audio track as finished so we won't wait for it.
```
Comment (wodin) [inline package/ios/Core/RecordingSession.swift:157]: *disabled

Comment (mrousavy) [reply package/ios/Core/RecordingSession.swift:157]: thanks!
