### PR TITLE
fix: camera initialization error (#3179)

### LINKED ISSUE #3179: 🐛 InitializationException - Device reporting less cameras than anticipated
### What's happening?

I am encountering a crash reported in Crashlytics, related to `androidx.camera.core.InitializationException`. The issue seems to occur when the app attempts to initialize the camera, and it reports fewer cameras than expected, resulting in a `CameraUnavailableException`. This crash happens on real devices, and it mentions retrying initialization. However, I cannot reproduce the issue locally on my test devices, so I’m unable to investigate further in a controlled environment.

### Reproduceable Code

```tsx
const QRCodeScanner: React.FC<QRCodeScannerProps> = ({
  onCodeScanned,
  loading,
  handlePermissionBlocked,
}) => {
  const device = useCameraDevice('back');
  const camera = useRef<Camera>(null);
  const isFocused = useIsFocused();
  const appState = useAppState();
  const [cameraReady, setCameraReady] = useState(false);
  const {onLayout, layout} = useLayout();
  const hasPermission = useCameraPermissions(handlePermissionBlocked);
  const codeScanner = useCodeScanner({
    codeTypes: ['qr'],
    onCodeScanned,
  });

  const isActive = isFocused && appState === 'active' && !!layout && !loading;
  const isScanning = isActive && cameraReady;

  const onError = (err: CameraRuntimeError | string) =>
    Analytics.logError(err, 'Camera error');

  return device && hasPermission ? (
    <View style={styles.container} onLayout={onLayout}>
      {isScanning ? (
        <QRMask
          containerHeight={layout.height}
          containerWidth={layout.width}
        />
      ) : null}
      {!isScanning ? (
        <View style={styles.loaderContainer}>
          <DefaultLoader />
        </View>
      ) : null}
      <Camera
        ref={camera}
        onError={onError}
        photo={false}
        device={device}
        codeScanner={codeScanner}
        isActive={isActive}
        style={StyleSheet.absoluteFill}
        onPreviewStarted={() => setCameraReady(true)}
        onStopped={() => setCameraReady(false)}
      />
    </View>
  ) : null;
};
```

### Relevant log output

```shell
Crashlytics report:

Fatal Exception: androidx.camera.core.InitializationException
androidx.camera.core.CameraUnavailableException: Device reporting less cameras than anticipated. On real devices: Retrying initialization might resolve temporary camera errors. On emulators: Ensure virtual camera configuration matches supported camera features as reported by PackageManager#hasSystemFeature. Available cameras: 0

androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX (CameraX.java:433)
```

### Camera Device

```
I cannot provide the JSON for the camera device since the issue occurs in production and I cannot reproduce it locally.
```

### Device

The crash affects multiple devices, with the following breakdown:  Motorola (69%) Samsung (17%) Xiaomi (14%). Operating system versions:  Android 11 (62%) Android 13 (21%) Android 12 (17%).

### VisionCamera Version

4.5.2

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by sorenfrederiksen**
## What

This PR prevents crashes caused by Android camera initialization exceptions, on devices without cameras.

## Changes

This PR ensures calls to `ProcessCameraProvider.getInstance(reactContext).await(executor)` are safely wrapped in a try-catch statement and logs resulting errors.

Please feel free to make changes to my edits and do with this what you will - really appreciate your work 🙏

#### Before 🐛

Catastrophic failure, resulting in a crash of the application.

https://github.com/user-attachments/assets/6e906c57-a377-4983-9b56-42c4f69726f2

#### After 🦋

Errors, but the app does not crash.

https://github.com/user-attachments/assets/447696f6-b626-46c9-b9d5-42bcf892b996

#### Before 🐛

No initialisation issues.

#### After 🦋

Still no initialisation issues.

https://github.com/user-attachments/assets/25079f14-7824-4a89-ab71-501a4b5b623c

## Related issues

Fixes #3179

### CODE REVIEW

File: package/android/src/main/java/com/mrousavy/camera/react/CameraDevicesManager.kt [hunk 1]
```diff
@@ -64,7 +64,13 @@ class CameraDevicesManager(private val reactContext: ReactApplicationContext) :
     cameraManager.registerAvailabilityCallback(callback, null)
     coroutineScope.launch {
       Log.i(TAG, "Initializing ProcessCameraProvider...")
-      cameraProvider = ProcessCameraProvider.getInstance(reactContext).await(executor)
+      cameraProvider = try {
+        ProcessCameraProvider.getInstance(reactContext).await(executor)
+      } catch (error: Throwable) {
+        Log.e(TAG, "Failed to get CameraProvider! Error: ${error.message}", error)
+        sendAvailableDevicesChangedEvent()
```
Comment (sorenfrederiksen) [inline package/android/src/main/java/com/mrousavy/camera/react/CameraDevicesManager.kt:71]: Not sure if we want to do this `sendAvailableDevicesChangedEvent()`, but I presumed sending the (empty, right?) devices array through would be expected behaviour, when we fail to initialise.

**Comment by mrousavy** [comment]
LGTM, thank you!

**Comment by mrousavy** [comment]
Released in [v4.6.4](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.6.4)! 🥳

**Comment by sorenfrederiksen** [comment]
> Released in [v4.6.4](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v4.6.4)! 🥳

Thank you! :D
