### PR TITLE
fix: Incorrect zoom on Android < 11

### LINKED ISSUE #1865: 🐛 Incorrect zoom on Android < 11
### What's happening?

Camera by default shows a zoomed preview and setting a larger zoom results in less zoom. For example, `zoom={4}` is less zoomed in than `zoom={1}`.

The issue is fixed if I replace the `Rect.zoomed` with:

```kotlin
fun Rect.zoomed(zoomFactor: Float): Rect {
  val dx = (width() / zoomFactor / 2).toInt()
  val dy = (height() / zoomFactor / 2).toInt()
  val left = centerX() - dx
  val top = centerY() - dy
  val right = centerX() + dx
  val bottom = centerY() + dy
  return Rect(left, top, right, bottom)
}
```

### Reproduceable Code

```tsx
const devices = Camera.getAvailableCameraDevices()
const device = devices.find((d) => d.position === 'front')

<Camera
  isActive
  device={device}
  style={StyleSheet.absoluteFill}
/>
```

### Relevant log output

```shell
/
```

### Camera Device

```json
{
  "sensorOrientation": "landscape-left",
  "hardwareLevel": "limited",
  "maxZoom": 4,
  "minZoom": 1,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "name": "FRONT (1)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "front",
  "id": "1"
}
```

### Device

Samsung Galaxy S8+ (Android 9)

### VisionCamera Version

3.1.0

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [X] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

### PR DESCRIPTION
**Pull request by touchmarine**
## What

This PR fixes incorrect zoom on Android < 11 and clamps zoom as out-of-bounds values can cause crashes (`zoom={0.5}` on Galaxy S8+). Additionally, iOS also clamps zoom so this makes it consistent.

## Changes

* Zoom cropping of camera preview and takePhoto() (Android < 11).
* Clamp zoom of camera preview and takePhoto() to camera device's min and max zoom (Android).

## Tested on

Samsung Galaxy S8+, Android 9

## Related issues

* Fixes #1865

### CODE REVIEW

**Comment by mrousavy** [comment]
Hey, thanks for your PR!

File: package/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt [hunk 1]
```diff
@@ -479,12 +479,20 @@ class CameraSession(
...
+    val zoomClamped = zoomRange.clamp(zoom)
     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
-      captureRequest.set(CaptureRequest.CONTROL_ZOOM_RATIO, zoom)
+      captureRequest.set(CaptureRequest.CONTROL_ZOOM_RATIO, zoomClamped)
     } else {
-      val cameraCharacteristics = cameraManager.getCameraCharacteristics(cameraId!!)
       val size = cameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_ACTIVE_ARRAY_SIZE)!!
-      captureRequest.set(CaptureRequest.SCALER_CROP_REGION, size.zoomed(zoom))
+      captureRequest.set(CaptureRequest.SCALER_CROP_REGION, size.zoomed(zoomClamped))
     }
```
Comment (mrousavy) [inline package/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt]: This entire thing is the same code as in `CameraDevice+createPhotoCaptureRequest` - let's move that to one place to avoid duplication.

Please create a file in `extensions/` called `CaptureRequest+setZoom.kt`, and add a Kotlin extension function like so:

```kt
fun CaptureRequest.setZoom(zoom: Double, cameraCharacteristics: CameraDeviceCharacteristics) {
  ...
```

Then implement the thing there.

File: package/android/src/main/java/com/mrousavy/camera/extensions/Rect+zoomed.kt [hunk 2]
```diff
@@ -3,12 +3,11 @@ package com.mrousavy.camera.extensions
...
-  val right = this.right - (width / zoomFactor / 2)
-  val bottom = this.bottom - (height / zoomFactor / 2)
-  return Rect(left.toInt(), top.toInt(), right.toInt(), bottom.toInt())
+  val dx = (width() / zoomFactor / 2).toInt()
+  val dy = (height() / zoomFactor / 2).toInt()
+  val left = centerX() - dx
+  val top = centerY() - dy
+  val right = centerX() + dx
+  val bottom = centerY() + dy
+  return Rect(left, top, right, bottom)
```
Comment (mrousavy) [inline package/android/src/main/java/com/mrousavy/camera/extensions/Rect+zoomed.kt:12]: What's the difference here? Does that still work for all cases?

**Review by mrousavy — CHANGES_REQUESTED** [review]

File: package/android/src/main/java/com/mrousavy/camera/extensions/Rect+zoomed.kt (hunk 2 above)
Comment (touchmarine) [reply package/android/src/main/java/com/mrousavy/camera/extensions/Rect+zoomed.kt:12]: The old code zoomed-out more the larger the zoomFactor was, this fixes this. It should work for the same cases, tested it on my device.

File: package/android/src/main/java/com/mrousavy/camera/extensions/CaptureRequest+setZoom.kt [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+        null
+      }
+      ) ?: Range(1f, cameraCharacteristics.get(CameraCharacteristics.SCALER_AVAILABLE_MAX_DIGITAL_ZOOM) ?: 1f)
+    val zoomClamped = zoomRange.clamp(zoom)
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
+      this.set(CaptureRequest.CONTROL_ZOOM_RATIO, zoomClamped)
+    } else {
+      val size = cameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_ACTIVE_ARRAY_SIZE)!!
+      this.set(CaptureRequest.SCALER_CROP_REGION, size.zoomed(zoomClamped))
+    }
```
Comment (mrousavy) [inline package/android/src/main/java/com/mrousavy/camera/extensions/CaptureRequest+setZoom.kt]:
```suggestion
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      val zoomRange = cameraCharacteristics.get(CameraCharacteristics.CONTROL_ZOOM_RATIO_RANGE) ?: Range(1f, 1f)
      val zoomClamped = zoomRange.clamp(zoom)
      this.set(CaptureRequest.CONTROL_ZOOM_RATIO, zoomClamped)
    } else {
      val maxZoom = cameraCharacteristics.get(CameraCharacteristics.SCALER_AVAILABLE_MAX_DIGITAL_ZOOM)
      val zoomRange = Range(1f, maxZoom ?: 1f)
      val size = cameraCharacteristics.get(CameraCharacteristics.SENSOR_INFO_ACTIVE_ARRAY_SIZE)!!
      val zoomClamped = zoomRange.clamp(zoom)
      this.set(CaptureRequest.SCALER_CROP_REGION, size.zoomed(zoomClamped))
    }
```

looks a bit cleaner imo as we only do one Build.VERSION check.

**Review by mrousavy — CHANGES_REQUESTED** [review]
just a minor code change, otherwise good to go!

**Comment by mrousavy** [comment]
Thanks man, released in 3.2.0!

**Comment by touchmarine** [comment]
Thanks!

Just downloaded it and a duplicate `FrameProcessorsUnavailableError` sneaked into `CameraError.kt`. After removing it, the build goes through :)

**Comment by mrousavy** [comment]
Wait what? Is there a bug on main?
If yes, can you submit a PR to fix that?

Thanks!
